// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IImpactProductNFT$Type } from "./IImpactProductNFT";
import { RecyclablesReward$Type } from "./RecyclablesReward";
import { Submission$Type } from "./Submission";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IImpactProductNFT"]: IImpactProductNFT$Type;
    ["RecyclablesReward"]: RecyclablesReward$Type;
    ["Submission"]: Submission$Type;
    ["contracts/contracts/Submission.sol:IImpactProductNFT"]: IImpactProductNFT$Type;
    ["contracts/contracts/Submission.sol:RecyclablesReward"]: RecyclablesReward$Type;
    ["contracts/contracts/Submission.sol:Submission"]: Submission$Type;
  }

  interface ContractTypesMap {
    ["IImpactProductNFT"]: GetContractReturnType<IImpactProductNFT$Type["abi"]>;
    ["RecyclablesReward"]: GetContractReturnType<RecyclablesReward$Type["abi"]>;
    ["Submission"]: GetContractReturnType<Submission$Type["abi"]>;
    ["contracts/contracts/Submission.sol:IImpactProductNFT"]: GetContractReturnType<IImpactProductNFT$Type["abi"]>;
    ["contracts/contracts/Submission.sol:RecyclablesReward"]: GetContractReturnType<RecyclablesReward$Type["abi"]>;
    ["contracts/contracts/Submission.sol:Submission"]: GetContractReturnType<Submission$Type["abi"]>;
  }
}
