// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IImpactProductNFT$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IImpactProductNFT",
  "sourceName": "contracts/contracts/Submission.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "_userHasMinted",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "getUserNFTData",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "tokenId",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "impact",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "level",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "safeMint",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "tokenId",
          "type": "uint256"
        }
      ],
      "name": "upgradeNFT",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "verifiedPOI",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "verifyPOI",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IImpactProductNFT",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IImpactProductNFT$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/contracts/Submission.sol:IImpactProductNFT",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IImpactProductNFT$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IImpactProductNFT",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IImpactProductNFT$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/contracts/Submission.sol:IImpactProductNFT",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IImpactProductNFT$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IImpactProductNFT",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IImpactProductNFT$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/contracts/Submission.sol:IImpactProductNFT",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IImpactProductNFT$Type["abi"]>>;
}
