// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RecyclablesReward$Type } from "./RecyclablesReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RecyclablesReward"]: RecyclablesReward$Type;
    ["contracts/contracts/RecyclablesReward.sol:RecyclablesReward"]: RecyclablesReward$Type;
  }

  interface ContractTypesMap {
    ["RecyclablesReward"]: GetContractReturnType<RecyclablesReward$Type["abi"]>;
    ["contracts/contracts/RecyclablesReward.sol:RecyclablesReward"]: GetContractReturnType<RecyclablesReward$Type["abi"]>;
  }
}
