// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ShortStrings$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ShortStrings",
  "sourceName": "@openzeppelin/contracts/utils/ShortStrings.sol",
  "abi": [
    {
      "inputs": [],
      "name": "InvalidShortString",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "string",
          "name": "str",
          "type": "string"
        }
      ],
      "name": "StringTooLong",
      "type": "error"
    }
  ],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220a24a02fe8c7cdaad9e90596b17963e3f33e33d656aa342a893d9100ab85ebc1c64736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea2646970667358221220a24a02fe8c7cdaad9e90596b17963e3f33e33d656aa342a893d9100ab85ebc1c64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ShortStrings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ShortStrings$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/ShortStrings.sol:ShortStrings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ShortStrings$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ShortStrings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ShortStrings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/ShortStrings.sol:ShortStrings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ShortStrings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ShortStrings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ShortStrings$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/ShortStrings.sol:ShortStrings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ShortStrings$Type["abi"]>>;
}
