// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDCUToken$Type } from "./IDCUToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDCUToken"]: IDCUToken$Type;
    ["contracts/contracts/interfaces/IDCUToken.sol:IDCUToken"]: IDCUToken$Type;
  }

  interface ContractTypesMap {
    ["IDCUToken"]: GetContractReturnType<IDCUToken$Type["abi"]>;
    ["contracts/contracts/interfaces/IDCUToken.sol:IDCUToken"]: GetContractReturnType<IDCUToken$Type["abi"]>;
  }
}
