// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DCUStorage$Type } from "./DCUStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DCUStorage"]: DCUStorage$Type;
    ["contracts/contracts/DCUStorage.sol:DCUStorage"]: DCUStorage$Type;
  }

  interface ContractTypesMap {
    ["DCUStorage"]: GetContractReturnType<DCUStorage$Type["abi"]>;
    ["contracts/contracts/DCUStorage.sol:DCUStorage"]: GetContractReturnType<DCUStorage$Type["abi"]>;
  }
}
