// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Base64$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Base64",
  "sourceName": "@openzeppelin/contracts/utils/Base64.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220076d33603b736f53401d1e60ef78cef0720938b0328366eaefbadb582aac61c164736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea2646970667358221220076d33603b736f53401d1e60ef78cef0720938b0328366eaefbadb582aac61c164736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Base64",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Base64$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Base64.sol:Base64",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Base64$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Base64",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Base64$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Base64.sol:Base64",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Base64$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Base64",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Base64$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Base64.sol:Base64",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Base64$Type["abi"]>>;
}
