// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDCUStorage$Type } from "./IDCUStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDCUStorage"]: IDCUStorage$Type;
    ["contracts/contracts/interfaces/IDCUStorage.sol:IDCUStorage"]: IDCUStorage$Type;
  }

  interface ContractTypesMap {
    ["IDCUStorage"]: GetContractReturnType<IDCUStorage$Type["abi"]>;
    ["contracts/contracts/interfaces/IDCUStorage.sol:IDCUStorage"]: GetContractReturnType<IDCUStorage$Type["abi"]>;
  }
}
