// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ERC721Utils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ERC721Utils",
  "sourceName": "@openzeppelin/contracts/token/ERC721/utils/ERC721Utils.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212204b64bb5d5241a618cd7612ab71d9946948c512e309098d3887235f3b370a440f64736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea26469706673582212204b64bb5d5241a618cd7612ab71d9946948c512e309098d3887235f3b370a440f64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ERC721Utils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC721Utils$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/token/ERC721/utils/ERC721Utils.sol:ERC721Utils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC721Utils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ERC721Utils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC721Utils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/token/ERC721/utils/ERC721Utils.sol:ERC721Utils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC721Utils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ERC721Utils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC721Utils$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/token/ERC721/utils/ERC721Utils.sol:ERC721Utils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC721Utils$Type["abi"]>>;
}
