// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface StorageSlot$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "StorageSlot",
  "sourceName": "@openzeppelin/contracts/utils/StorageSlot.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212205466ee9e89c1a28ab137c75d845a27b882f8eadbda10820c884189f0c28dc77964736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea26469706673582212205466ee9e89c1a28ab137c75d845a27b882f8eadbda10820c884189f0c28dc77964736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "StorageSlot",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "StorageSlot",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<StorageSlot$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<StorageSlot$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "StorageSlot",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;
}
