// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDCUNftRewardManager$Type } from "./IDCUNftRewardManager";
import { ImpactProductNFT$Type } from "./ImpactProductNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDCUNftRewardManager"]: IDCUNftRewardManager$Type;
    ["ImpactProductNFT"]: ImpactProductNFT$Type;
    ["contracts/contracts/tokens/ImpactProductNFT.sol:IDCUNftRewardManager"]: IDCUNftRewardManager$Type;
    ["contracts/contracts/tokens/ImpactProductNFT.sol:ImpactProductNFT"]: ImpactProductNFT$Type;
  }

  interface ContractTypesMap {
    ["IDCUNftRewardManager"]: GetContractReturnType<IDCUNftRewardManager$Type["abi"]>;
    ["ImpactProductNFT"]: GetContractReturnType<ImpactProductNFT$Type["abi"]>;
    ["contracts/contracts/tokens/ImpactProductNFT.sol:IDCUNftRewardManager"]: GetContractReturnType<IDCUNftRewardManager$Type["abi"]>;
    ["contracts/contracts/tokens/ImpactProductNFT.sol:ImpactProductNFT"]: GetContractReturnType<ImpactProductNFT$Type["abi"]>;
  }
}
