// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IDCUNftRewardManager$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IDCUNftRewardManager",
  "sourceName": "contracts/contracts/tokens/ImpactProductNFT.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "level",
          "type": "uint256"
        }
      ],
      "name": "rewardImpactProductClaim",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        },
        {
          "internalType": "bool",
          "name": "status",
          "type": "bool"
        }
      ],
      "name": "setPoiVerificationStatus",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        },
        {
          "internalType": "bool",
          "name": "hasMinted",
          "type": "bool"
        }
      ],
      "name": "updateNftMintStatus",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IDCUNftRewardManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IDCUNftRewardManager$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/contracts/tokens/ImpactProductNFT.sol:IDCUNftRewardManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IDCUNftRewardManager$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IDCUNftRewardManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IDCUNftRewardManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/contracts/tokens/ImpactProductNFT.sol:IDCUNftRewardManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IDCUNftRewardManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IDCUNftRewardManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IDCUNftRewardManager$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/contracts/tokens/ImpactProductNFT.sol:IDCUNftRewardManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IDCUNftRewardManager$Type["abi"]>>;
}
