// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DCUToken$Type } from "./DCUToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DCUToken"]: DCUToken$Type;
    ["contracts/contracts/tokens/DCUToken.sol:DCUToken"]: DCUToken$Type;
  }

  interface ContractTypesMap {
    ["DCUToken"]: GetContractReturnType<DCUToken$Type["abi"]>;
    ["contracts/contracts/tokens/DCUToken.sol:DCUToken"]: GetContractReturnType<DCUToken$Type["abi"]>;
  }
}
