// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DCUAccounting$Type } from "./DCUAccounting";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DCUAccounting"]: DCUAccounting$Type;
    ["contracts/contracts/DCUAccounting.sol:DCUAccounting"]: DCUAccounting$Type;
  }

  interface ContractTypesMap {
    ["DCUAccounting"]: GetContractReturnType<DCUAccounting$Type["abi"]>;
    ["contracts/contracts/DCUAccounting.sol:DCUAccounting"]: GetContractReturnType<DCUAccounting$Type["abi"]>;
  }
}
