// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { INFTCollection$Type } from "./INFTCollection";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["INFTCollection"]: INFTCollection$Type;
    ["contracts/contracts/interfaces/INFTCollection.sol:INFTCollection"]: INFTCollection$Type;
  }

  interface ContractTypesMap {
    ["INFTCollection"]: GetContractReturnType<INFTCollection$Type["abi"]>;
    ["contracts/contracts/interfaces/INFTCollection.sol:INFTCollection"]: GetContractReturnType<INFTCollection$Type["abi"]>;
  }
}
