// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface INFTCollection$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "INFTCollection",
  "sourceName": "contracts/contracts/interfaces/INFTCollection.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "owner",
          "type": "address"
        }
      ],
      "name": "balanceOf",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "hasMinted",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "to",
          "type": "address"
        }
      ],
      "name": "mint",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "rewardsContract",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "INFTCollection",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<INFTCollection$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/contracts/interfaces/INFTCollection.sol:INFTCollection",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<INFTCollection$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "INFTCollection",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<INFTCollection$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/contracts/interfaces/INFTCollection.sol:INFTCollection",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<INFTCollection$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "INFTCollection",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<INFTCollection$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/contracts/interfaces/INFTCollection.sol:INFTCollection",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<INFTCollection$Type["abi"]>>;
}
