// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NFTCollection$Type } from "./NFTCollection";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NFTCollection"]: NFTCollection$Type;
    ["contracts/contracts/tokens/NFTCollection.sol:NFTCollection"]: NFTCollection$Type;
  }

  interface ContractTypesMap {
    ["NFTCollection"]: GetContractReturnType<NFTCollection$Type["abi"]>;
    ["contracts/contracts/tokens/NFTCollection.sol:NFTCollection"]: GetContractReturnType<NFTCollection$Type["abi"]>;
  }
}
