// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface MessageHashUtils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "MessageHashUtils",
  "sourceName": "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea264697066735822122005bcca6475580c90c64cf279516a18a4b1e362c33ce8432f1612dffc92601d3364736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea264697066735822122005bcca6475580c90c64cf279516a18a4b1e362c33ce8432f1612dffc92601d3364736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "MessageHashUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MessageHashUtils$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol:MessageHashUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MessageHashUtils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "MessageHashUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MessageHashUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol:MessageHashUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MessageHashUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "MessageHashUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MessageHashUtils$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol:MessageHashUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MessageHashUtils$Type["abi"]>>;
}
