// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DCURewardManager$Type } from "./DCURewardManager";
import { ISubmissionHypercerts$Type } from "./ISubmissionHypercerts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DCURewardManager"]: DCURewardManager$Type;
    ["ISubmissionHypercerts"]: ISubmissionHypercerts$Type;
    ["contracts/contracts/DCURewardManager.sol:DCURewardManager"]: DCURewardManager$Type;
    ["contracts/contracts/DCURewardManager.sol:ISubmissionHypercerts"]: ISubmissionHypercerts$Type;
  }

  interface ContractTypesMap {
    ["DCURewardManager"]: GetContractReturnType<DCURewardManager$Type["abi"]>;
    ["ISubmissionHypercerts"]: GetContractReturnType<ISubmissionHypercerts$Type["abi"]>;
    ["contracts/contracts/DCURewardManager.sol:DCURewardManager"]: GetContractReturnType<DCURewardManager$Type["abi"]>;
    ["contracts/contracts/DCURewardManager.sol:ISubmissionHypercerts"]: GetContractReturnType<ISubmissionHypercerts$Type["abi"]>;
  }
}
