// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ISubmissionHypercerts$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ISubmissionHypercerts",
  "sourceName": "contracts/contracts/DCURewardManager.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "userHypercertCount",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ISubmissionHypercerts",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISubmissionHypercerts$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/contracts/DCURewardManager.sol:ISubmissionHypercerts",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISubmissionHypercerts$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ISubmissionHypercerts",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISubmissionHypercerts$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/contracts/DCURewardManager.sol:ISubmissionHypercerts",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISubmissionHypercerts$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ISubmissionHypercerts",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISubmissionHypercerts$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/contracts/DCURewardManager.sol:ISubmissionHypercerts",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISubmissionHypercerts$Type["abi"]>>;
}
